import { Country } from './types'
import { visaRules } from './visa-rules'

// Enhanced countries with visa information for US passport holders
export const countriesWithVisa: Country[] = [
  // Africa
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, info: 'Visa required in advance' } },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, eVisa: true, info: 'E-visa required' } },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const, eVisa: true, visaOnArrival: true } },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', color: 'sky', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, eVisa: true } },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', color: 'green', visa: { maxDays: 45, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'CD', name: 'Congo (DRC)', flag: '🇨🇩', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, eVisa: true } },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', color: 'orange', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true } },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', color: 'blue', visa: { maxDays: 31, ruleType: 'reset' as const, eVisa: true, visaOnArrival: true } },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', color: 'red', visa: visaRules.EG ? { ...visaRules.EG, visaOnArrival: true, eVisa: true } : { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true, visaOnArrival: true } },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true } },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', color: 'red', visa: { maxDays: 21, ruleType: 'reset' as const } },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', color: 'yellow', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, eVisa: true } },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', color: 'yellow', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eta: true, info: 'eTA required ($32.50)' } },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', color: 'blue', visa: { maxDays: 14, ruleType: 'reset' as const } },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', color: 'red', visa: { maxDays: 60, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', color: 'red', visa: visaRules.MA || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', color: 'orange', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, eVisa: true } },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹', color: 'green', visa: { maxDays: 15, ruleType: 'reset' as const, eVisa: true } },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', color: 'green', visa: visaRules.ZA || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true, info: 'Visa on arrival ($50) or e-visa' } },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', color: 'green', visa: { maxDays: 7, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },

  // Americas
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', color: 'red', visa: { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', color: 'sky', visa: visaRules.AR || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', color: 'blue', visa: { maxDays: 240, ruleType: 'reset' as const } },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', color: 'blue', visa: { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true, info: 'Visa on arrival ($160)' } },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', color: 'green', visa: visaRules.BR || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', color: 'red', visa: visaRules.CA || { maxDays: 180, periodDays: 365, ruleType: 'rolling' as const } },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', color: 'blue', visa: visaRules.CL || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', color: 'yellow', visa: visaRules.CO || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', color: 'blue', visa: visaRules.CR || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, requiresVisa: true, info: 'Tourist Card required' } },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', color: 'green', visa: { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', color: 'yellow', visa: visaRules.EC || { maxDays: 90, periodDays: 365, ruleType: 'rolling' as const } },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', color: 'green', visa: { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', color: 'emerald', visa: visaRules.MX || { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', color: 'blue', visa: visaRules.PA || { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', color: 'red', visa: visaRules.PE || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', color: 'blue', visa: { maxDays: 42, ruleType: 'reset' as const } },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true, info: 'E-visa required' } },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'US', name: 'United States', flag: '🇺🇸', color: 'blue', visa: visaRules.US || { maxDays: 9999, ruleType: 'reset' as const, info: 'Home country' } },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', color: 'blue', visa: visaRules.UY || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', color: 'yellow', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },

  // Asia
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', color: 'red', visa: { maxDays: 180, ruleType: 'reset' as const } },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const, eVisa: true, info: 'E-visa required' } },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', color: 'red', visa: { maxDays: 14, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', color: 'orange', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, info: 'Tour package required' } },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', color: 'yellow', visa: { maxDays: 30, ruleType: 'reset' as const, eta: true } },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', color: 'indigo', visa: visaRules.KH || { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'CN', name: 'China', flag: '🇨🇳', color: 'red', visa: visaRules.CN || { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', color: 'red', visa: { maxDays: 365, ruleType: 'reset' as const, info: '1 year visa-free' } },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', color: 'rose', visa: visaRules.HK || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'IN', name: 'India', flag: '🇮🇳', color: 'orange', visa: visaRules.IN || { maxDays: 60, ruleType: 'reset' as const, eVisa: true, requiresVisa: true } },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', color: 'red', visa: visaRules.ID || { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', color: 'blue', visa: visaRules.IL || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', color: 'pink', visa: visaRules.JP || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', color: 'sky', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, info: 'Tour required' } },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', color: 'purple', visa: visaRules.KR || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true } },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', color: 'red', visa: { maxDays: 60, ruleType: 'reset' as const } },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', color: 'blue', visa: visaRules.LA || { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', color: 'green', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', color: 'cyan', visa: visaRules.MY || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', color: 'yellow', visa: visaRules.MM || { maxDays: 28, ruleType: 'reset' as const, eVisa: true, requiresVisa: true } },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, eVisa: true } },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true, eVisa: true } },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', color: 'red', visa: { maxDays: 90, ruleType: 'reset' as const, info: 'Entry via Israel or Jordan' } },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', color: 'blue', visa: visaRules.PH || { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', color: 'purple', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const, eVisa: true } },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', color: 'red', visa: visaRules.SG || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', color: 'amber', visa: visaRules.LK || { maxDays: 30, ruleType: 'reset' as const, eta: true } },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', color: 'violet', visa: visaRules.TW || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', color: 'red', visa: { maxDays: 45, ruleType: 'reset' as const, eVisa: true } },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', color: 'orange', visa: visaRules.TH || { maxDays: 60, ruleType: 'reset' as const } },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const, visaOnArrival: true } },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', color: 'red', visa: visaRules.TR || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', color: 'green', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', color: 'green', visa: visaRules.AE || { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', color: 'yellow', visa: visaRules.VN || { maxDays: 90, ruleType: 'reset' as const, eVisa: true, requiresVisa: true } },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', color: 'red', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },

  // Europe (Schengen countries share 90/180 rule)
  { code: 'AL', name: 'Albania', flag: '🇦🇱', color: 'red', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', color: 'red', visa: visaRules.AT || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', color: 'amber', visa: visaRules.BE || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', color: 'green', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', color: 'blue', visa: visaRules.HR || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', color: 'orange', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', color: 'blue', visa: visaRules.CZ || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', color: 'red', visa: visaRules.DK || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', color: 'blue', visa: visaRules.EE || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', color: 'blue', visa: visaRules.FI || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'FR', name: 'France', flag: '🇫🇷', color: 'indigo', visa: visaRules.FR || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', color: 'amber', visa: visaRules.DE || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', color: 'blue', visa: visaRules.GR || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', color: 'green', visa: visaRules.HU || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', color: 'blue', visa: visaRules.IS || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', color: 'lime', visa: visaRules.IE || { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', color: 'teal', visa: visaRules.IT || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', color: 'red', visa: visaRules.LV || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', color: 'yellow', visa: visaRules.LT || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', color: 'sky', visa: visaRules.LU || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', color: 'red', visa: visaRules.MT || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', color: 'red', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', color: 'red', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', color: 'orange', visa: visaRules.NL || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', color: 'red', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', color: 'red', visa: visaRules.NO || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', color: 'red', visa: visaRules.PL || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', color: 'green', visa: visaRules.PT || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', color: 'blue', visa: visaRules.RO || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', color: 'red', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', color: 'blue', visa: visaRules.SK || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', color: 'blue', visa: visaRules.SI || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', color: 'yellow', visa: visaRules.ES || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', color: 'blue', visa: visaRules.SE || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', color: 'red', visa: visaRules.CH || { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', color: 'blue', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', color: 'slate', visa: visaRules.GB || { maxDays: 180, periodDays: 365, ruleType: 'rolling' as const } },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦', color: 'yellow', visa: { maxDays: 90, periodDays: 180, ruleType: 'rolling' as const } },

  // Oceania
  { code: 'AU', name: 'Australia', flag: '🇦🇺', color: 'emerald', visa: visaRules.AU || { maxDays: 90, ruleType: 'reset' as const, eta: true } },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', color: 'sky', visa: { maxDays: 120, ruleType: 'reset' as const } },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', color: 'blue', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', color: 'blue', visa: { maxDays: 0, ruleType: 'reset' as const, requiresVisa: true } },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', color: 'sky', visa: visaRules.NZ || { maxDays: 90, ruleType: 'reset' as const, eta: true } },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', color: 'red', visa: { maxDays: 60, ruleType: 'reset' as const, visaOnArrival: true, eVisa: true } },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', color: 'red', visa: { maxDays: 60, ruleType: 'reset' as const } },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', color: 'green', visa: { maxDays: 90, ruleType: 'reset' as const } },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', color: 'red', visa: { maxDays: 31, ruleType: 'reset' as const } },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', color: 'blue', visa: { maxDays: 30, ruleType: 'reset' as const } },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', color: 'red', visa: { maxDays: 30, ruleType: 'reset' as const } },
].sort((a, b) => a.name.localeCompare(b.name))

export function getCountryByCode(code: string): Country | undefined {
  return countriesWithVisa.find(c => c.code === code)
}

// Color-blind friendly color mapping with high contrast
export function getCountryColor(countryCode: string): string {
  const country = getCountryByCode(countryCode)
  if (!country) return 'bg-gray-500'
  
  const colorMap: Record<string, string> = {
    red: 'bg-red-500',
    orange: 'bg-orange-500', 
    yellow: 'bg-yellow-500',
    amber: 'bg-amber-500',
    lime: 'bg-lime-500',
    green: 'bg-green-500',
    emerald: 'bg-emerald-500',
    teal: 'bg-teal-500',
    cyan: 'bg-cyan-500',
    sky: 'bg-sky-500',
    blue: 'bg-blue-500',
    indigo: 'bg-indigo-600',
    violet: 'bg-violet-500',
    purple: 'bg-purple-500',
    pink: 'bg-pink-500',
    rose: 'bg-rose-500',
    slate: 'bg-slate-500',
  }
  
  return colorMap[country.color] || 'bg-gray-500'
}